jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - continue-on-error: true
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - continue-on-error: true
      name: Set up Java
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Build with Maven
      run: mvn --batch-mode --update-snapshots verify
    - continue-on-error: true
      if: ${{ matrix.java == '17' }}
      name: Upload JAR
      uses: actions/upload-artifact@v4
      with:
        name: commafeed.jar
        path: commafeed-server/target/commafeed.jar
    - continue-on-error: true
      if: ${{ matrix.java == '17' && (github.ref_type == 'tag' || github.ref_name
        == 'master') }}
      name: Login to Container Registry
      uses: docker/login-action@v3
      with:
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
    - continue-on-error: true
      if: ${{ matrix.java == '17' && github.ref_type == 'tag' }}
      name: Docker build and push tag
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
        push: false
        tags: 'athou/commafeed:latest

          athou/commafeed:${{ github.ref_name }}

          '
    - continue-on-error: true
      if: ${{ matrix.java == '17' && github.ref_name == 'master' }}
      name: Docker build and push master
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
        push: false
        tags: athou/commafeed:master
    - continue-on-error: true
      id: changelog_reader
      if: ${{ matrix.java == '17' && github.ref_type == 'tag' }}
      name: Extract Changelog Entry
      uses: mindsers/changelog-reader-action@v2
      with:
        version: ${{ github.ref_name }}
    - continue-on-error: true
      if: ${{ matrix.java == '17' && github.ref_type == 'tag' }}
      name: Create GitHub release
      uses: softprops/action-gh-release@v2
      with:
        body: ${{ steps.changelog_reader.outputs.changes }}
        draft: false
        files: 'commafeed-server/target/commafeed.jar

          commafeed-server/config.yml.example

          '
        name: CommaFeed ${{ github.ref_name }}
        prerelease: false
    strategy:
      matrix:
        java:
        - '17'
        - '21'
name: Java CI
on:
  repository_dispatch:
    types: trigger-ga___build.yml
